# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e12b4e3c66a60c040b68c8090faa52be"
name = "cloudhouse-widget"
handle = "cloudhouse-widget-1"
application_url = "https://flowers-hardware-brandon-commentary.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://flowers-hardware-brandon-commentary.trycloudflare.com/auth/callback",
  "https://flowers-hardware-brandon-commentary.trycloudflare.com/auth/shopify/callback",
  "https://flowers-hardware-brandon-commentary.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
